function com_haulmont_cuba_web_toolkit_ui_WidgetSet(){var O='bootstrap',P='begin',Q='gwt.codesvr.com.haulmont.cuba.web.toolkit.ui.WidgetSet=',R='gwt.codesvr=',S='com.haulmont.cuba.web.toolkit.ui.WidgetSet',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='Chrome',gb='eval("',hb='");',ib='script',jb='javascript',kb='moduleStartup',lb='moduleRequested',mb='com_haulmont_cuba_web_toolkit_ui_WidgetSet',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='com.haulmont.cuba.web.toolkit.ui.WidgetSet::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='com.haulmont.cuba.web.toolkit.ui.WidgetSet.nocache.js',Ib='base',Jb='//',Kb='ie11orHigher',Lb='MSIE',Mb='Trident',Nb='yes',Ob='no',Pb='modernie',Qb='none',Rb='user.agent',Sb='webkit',Tb='safari',Ub='msie',Vb=11,Wb='ie10',Xb=9,Yb='ie9',Zb=8,$b='ie8',_b='gecko',ac='gecko1_8',bc=2,cc=3,dc=4,ec='selectingPermutation',fc='com.haulmont.cuba.web.toolkit.ui.WidgetSet.devmode.js',gc='628242BD69E7CA80806A951678C720D4',hc=':1',ic=':10',jc=':11',kc=':2',lc=':3',mc=':4',nc=':5',oc=':6',pc=':7',qc=':8',rc=':9',sc=':',tc='.cache.js',uc='link',vc='rel',wc='stylesheet',xc='href',yc='loadExternalRefs',zc='popupbutton/popupbutton.css',Ac='fi_jasoft_dragdroplayouts/dragdroplayouts.css',Bc='end',Cc='http:',Dc='file:',Ec='_gwt_dummy_',Fc='__gwtDevModeHook:com.haulmont.cuba.web.toolkit.ui.WidgetSet',Gc='Ignoring non-whitelisted Dev Mode URL: ',Hc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_haulmont_cuba_web_toolkit_ui_WidgetSet.__sendStats=r;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__moduleName=S;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__errFn=null;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__moduleBase=U;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__softPermutationId=V;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__computePropValue=null;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__getPropMap=null;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__installRunAsyncCode=function(){};com_haulmont_cuba_web_toolkit_ui_WidgetSet.__gwtStartLoadingFragment=function(){return null};com_haulmont_cuba_web_toolkit_ui_WidgetSet.__gwt_isKnownPropertyValue=function(){return false};com_haulmont_cuba_web_toolkit_ui_WidgetSet.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};com_haulmont_cuba_web_toolkit_ui_WidgetSet.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[com_haulmont_cuba_web_toolkit_ui_WidgetSet.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.id=S;a.style.cssText=Y+Z;a.tabIndex=-1;p.body.appendChild(a);u=a.contentWindow.document;u.open();var b=document.compatMode==$?_:ab;u.write(b+bb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==cb){return typeof p.body!=cb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(p.removeEventListener){p.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(gb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(hb));g=e.createElement(ib);g.language=jb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(ib);g.language=jb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_haulmont_cuba_web_toolkit_ui_WidgetSet.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;if(com_haulmont_cuba_web_toolkit_ui_WidgetSet.__errFn){n.onerror=function(){com_haulmont_cuba_web_toolkit_ui_WidgetSet.__errFn(mb,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
com_haulmont_cuba_web_toolkit_ui_WidgetSet.__startLoadingFragment=function(a){return D(a)};com_haulmont_cuba_web_toolkit_ui_WidgetSet.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(ib);d.language=jb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,ab);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=ab}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;com_haulmont_cuba_web_toolkit_ui_WidgetSet.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return ab}
function h(){var a=p.getElementsByTagName(ib);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return ab}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_haulmont_cuba_web_toolkit_ui_WidgetSet.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){{var a=o.navigator.userAgent;if(a.indexOf(Lb)==-1&&a.indexOf(Mb)!=-1){return Nb}return Ob}};i[Kb]={'no':V,'yes':W};j[Pb]=function(){{var a=o.navigator.userAgent;if(a.indexOf(Lb)==-1&&a.indexOf(Mb)!=-1){return Nb}return Qb}};i[Pb]={'none':V,'yes':W};j[Rb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Sb)!=-1}())return Tb;if(function(){return a.indexOf(Ub)!=-1&&(b>=eb&&b<Vb)}())return Wb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Xb&&b<Vb)}())return Yb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Zb&&b<Vb)}())return $b;if(function(){return a.indexOf(_b)!=-1||b>=Vb}())return ac;return Tb};i[Rb]={'gecko1_8':V,'ie10':W,'ie8':bc,'ie9':cc,'safari':dc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};com_haulmont_cuba_web_toolkit_ui_WidgetSet.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};com_haulmont_cuba_web_toolkit_ui_WidgetSet.__computePropValue=k;o.__gwt_activeModules[S].bindings=com_haulmont_cuba_web_toolkit_ui_WidgetSet.__getPropMap;r(O,ec);if(q()){return D(fc)}var l;try{h([Ob,Qb,ac],gc);h([Ob,Nb,ac],gc+hc);h([Nb,Qb,Yb],gc+ic);h([Nb,Qb,Tb],gc+jc);h([Ob,Qb,Wb],gc+kc);h([Ob,Qb,$b],gc+lc);h([Ob,Qb,Yb],gc+mc);h([Ob,Qb,Tb],gc+nc);h([Nb,Qb,ac],gc+oc);h([Nb,Nb,ac],gc+pc);h([Nb,Qb,Wb],gc+qc);h([Nb,Qb,$b],gc+rc);l=f[k(Kb)][k(Pb)][k(Rb)];var m=l.indexOf(sc);if(m!=-1){g=parseInt(l.substring(m+W),eb);l=l.substring(V,m)}}catch(a){}com_haulmont_cuba_web_toolkit_ui_WidgetSet.__softPermutationId=g;return D(l+tc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(uc);b.setAttribute(vc,wc);b.setAttribute(xc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(yc,P);c(zc);c(Ac);r(yc,Bc)}
B();com_haulmont_cuba_web_toolkit_ui_WidgetSet.__moduleBase=C();t[S].moduleBase=com_haulmont_cuba_web_toolkit_ui_WidgetSet.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Cc||o.location.protocol==Dc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Ec;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Fc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Gc+L)}L=ab}if(L&&!o[K]){o[K]=true;o[K+Hc]=C();var M=p.createElement(ib);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Bc);A(H);return true}
com_haulmont_cuba_web_toolkit_ui_WidgetSet.succeeded=com_haulmont_cuba_web_toolkit_ui_WidgetSet();