alter table ALMAUTO_EMPLOYEE add constraint FK_ALMAUTO_EMPLOYEE_COMPANY foreign key (COMPANY_ID) references ALMAUTO_COMPANY(ID);
alter table ALMAUTO_EMPLOYEE add constraint FK_ALMAUTO_EMPLOYEE_POST foreign key (POST_ID) references ALMAUTO_POST(ID);
alter table ALMAUTO_EMPLOYEE add constraint FK_ALMAUTO_EMPLOYEE_BRANCH foreign key (BRANCH_ID) references ALMAUTO_BRANCH(ID);
alter table ALMAUTO_EMPLOYEE add constraint FK_ALMAUTO_EMPLOYEE_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ALMAUTO_EMPLOYEE_COMPANY on ALMAUTO_EMPLOYEE (COMPANY_ID);
create index IDX_ALMAUTO_EMPLOYEE_POST on ALMAUTO_EMPLOYEE (POST_ID);
create index IDX_ALMAUTO_EMPLOYEE_BRANCH on ALMAUTO_EMPLOYEE (BRANCH_ID);
create index IDX_ALMAUTO_EMPLOYEE_USER on ALMAUTO_EMPLOYEE (USER_ID);
