alter table ALMAUTO_PRODUCT_IN add constraint FK_ALMAUTO_PRODUCT_IN_WAREHOUSE foreign key (WAREHOUSE_ID) references ALMAUTO_WAREHOUSE(ID);
alter table ALMAUTO_PRODUCT_IN add constraint FK_ALMAUTO_PRODUCT_IN_PRICE foreign key (PRICE_ID) references ALMAUTO_PRICE(ID);
create index IDX_ALMAUTO_PRODUCT_IN_WAREHOUSE on ALMAUTO_PRODUCT_IN (WAREHOUSE_ID);
create index IDX_ALMAUTO_PRODUCT_IN_PRICE on ALMAUTO_PRODUCT_IN (PRICE_ID);
