alter table ALMAUTO_PACK_COUNT add constraint FK_ALMAUTO_PACK_COUNT_PACKAGE_TYPE foreign key (PACKAGE_TYPE_ID) references ALMAUTO_PACKAGE_TYPE(ID);
alter table ALMAUTO_PACK_COUNT add constraint FK_ALMAUTO_PACK_COUNT_PRODUCTS foreign key (PRODUCTS_ID) references ALMAUTO_PRODUCTS(ID);
create index IDX_ALMAUTO_PACK_COUNT_PACKAGE_TYPE on ALMAUTO_PACK_COUNT (PACKAGE_TYPE_ID);
create index IDX_ALMAUTO_PACK_COUNT_PRODUCTS on ALMAUTO_PACK_COUNT (PRODUCTS_ID);
