alter table ALMAUTO_PRODUCTS add constraint FK_ALMAUTO_PRODUCTS_PRODUCT_TYPE foreign key (PRODUCT_TYPE_ID) references ALMAUTO_PRODUCT_TYPE(ID);
alter table ALMAUTO_PRODUCTS add constraint FK_ALMAUTO_PRODUCTS_UNIT foreign key (UNIT_ID) references ALMAUTO_UNIT(ID);
create index IDX_ALMAUTO_PRODUCTS_PRODUCT_TYPE on ALMAUTO_PRODUCTS (PRODUCT_TYPE_ID);
create index IDX_ALMAUTO_PRODUCTS_UNIT on ALMAUTO_PRODUCTS (UNIT_ID);
